spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: ${API_DOCS_PATH}
    enable-spring-security: true
    default-consumes-media-type: application/json
    default-produces-media-type: application/json
